on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release please action

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: googleapis/release-please-action@v3
        with:
          release-type: simple
          config-file: .github/release-please-config.json
          # skip-labeling: true
